### ISSUE TITLE
Prepare a recording as offline tutorial

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler-action#15]
Prepare a recording as offline tutorial or use for CNCF TAG presentation: prepare offline recording (5min each) and reserve a 15-20min TAG meeting time for presentation.

**Comment by SamYuan1990** [comment]
https://www.bilibili.com/video/BV11v4y1y7eQ/ @jiangphcn , @rootfs what do you think of?

**Comment by SamYuan1990** [comment]
https://www.bilibili.com/video/BV1f84y1K7Pb/ @rootfs , @jiangphcn here is latest version.

**Comment by jiangphcn** [comment]
Good stuff. Here is about Kepler deployment with Helm Chart: https://www.bilibili.com/video/BV1xM4y1m7Ti/.
