### ISSUE TITLE
Rename action to `kepler-action`

### ISSUE THREAD

**Issue by nikimanoledaki** [sustainable-computing-io/kepler-action#17]
As mentioned in [this](https://github.com/sustainable-computing-io/kepler/pull/445/files#r1071970644) review comment, here is my suggestion:

> I suggest renaming the action to `sustainable-computing-io/kepler-action` so that it's lowercase, kebab-case, and a bit simplified, to follow the naming pattern of other GitHub Actions such as [release-drafter](https://github.com/marketplace/actions/release-drafter), [create-pull-request](https://github.com/marketplace/actions/create-pull-request), etc.

This would require renaming the repo's title and any mentions of the action in this and other repos.

Happy to discuss this further :)

**Comment by rootfs** [comment]
done

**Comment by SamYuan1990** [comment]
@rootfs , I am not sure if we should rename as `kepler-action` or `kepler-k8s-action` or `k8s-action`?
this repo is just a github action for sustainable-computing-io org's repos usage to create k8s cluster in kind for CI usage.
if we name as `kepler-action`? does it misunderstanding for external user?
