### ISSUE TITLE
clean version value without any default

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler-action#20]
```
kepler
action
https://github.com/sustainable-computing-io/local-dev-cluster
```
if we want to have a script based script to support both CI and local cluster, to ensure a central place for parameters. for example version of cli(`kubectl`) 
action should not keep any version and just receive those value from upstream as kepler and pass it to local-dev-cluster
versions can be management via 
`settings/variables/actions` from repos to avoid code change.

**Comment by SamYuan1990** [comment]
the default value should be moved to local-dev-cluster repo.
@rootfs pls add local-dev-cluster repo to CNCF apply issue.

**Comment by rootfs** [comment]
yes, a cluster repo will separate cluster setup and its consumers cleanly. Kepler projects can use the cluster repo to setup a local dev env in the same way as the CI. When new cluster types are added, they don't affect other repos.

@SamYuan1990 once the scripts are moved to cluster repo, let's add it to the sandbox application.
