### ISSUE TITLE
Bump up Kepler-action version

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-action#55]
Since we added support for Microshift to Kepler-action. In order for Kepler repo and Kepler-Operator repo's CI to work it would be best to have a bump up in the version.

CC: @rootfs @SamYuan1990

**Comment by rootfs** [comment]
@SamYuan1990 this looks a good opportunity to merge the open PRs and create a new release

**Comment by SamYuan1990** [comment]
@rootfs , @vprashar2929 , do we need to wait for #50 ?

**Comment by SamYuan1990** [comment]
otherwise, I will bump up the version this weekend.

**Comment by vprashar2929** [comment]
IMHO it's still very unclear as to whether ProwCI would be a great fit provided the lack of understanding we have around it and whether it would be easy to integrate it or not. I am also in favor of testing Kepler against different OS and platforms. If it will take more time to come to a consensus with https://github.com/sustainable-computing-io/kepler-action/issues/50 I think we can bump up the version with whatever we have till now as it will be inclined with version to local-dev-cluster. Wdyt?

**Comment by SamYuan1990** [comment]
> IMHO it's still very unclear as to whether ProwCI would be a great fit provided the lack of understanding we have around it and whether it would be easy to integrate it or not. I am also in favor of testing Kepler against different OS and platforms. If it will take more time to come to a consensus with #50 I think we can bump up the version with whatever we have till now as it will be inclined with version to local-dev-cluster. Wdyt?

em... I suppose we need point our CI to v0.0.1 as #57
as the reason, when we try to bump up version of this repo, we want to points to the specific version used for local-dev-cluster. and test it, if the test is passed, we are confidence to apply the change to kepler, operator, and helm chart etc.

**Comment by SamYuan1990** [comment]
we can bump up version once #57 is merged as a checkpoint.

**Comment by SamYuan1990** [comment]
ok as #57 is merged, WIP to bump up kepler-action version.

**Comment by SamYuan1990** [comment]
close with https://github.com/sustainable-computing-io/kepler-action/tree/v0.0.1
